name: salama
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.0
  intl: ^0.17.0
  mockito: ^5.1.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  modal_progress_hud: ^0.1.3
  flutter_map: ^0.14.0
  google_sign_in: ^5.2.4
  firebase_database: ^9.0.7
  http: ^0.13.4
  encrypt: ^5.0.1
  google_maps_flutter: ^2.1.1
  pin_code_fields: ^7.3.0
  location: ^4.3.0
  provider: ^6.0.2
  geolocator: ^8.0.0
  auto_search: ^1.0.6
  onesignal_flutter: ^3.3.0
  workmanager: ^0.4.1
  google_places_for_flutter: ^1.0.1
  #  uuid: ^2.0.4
  flutter_google_places: ^0.3.0
  flutter_spinkit: ^5.1.0
  firebase_messaging: ^11.2.12
  overlay_support: ^1.2.1
  google_maps_webservice: ^0.0.19
  #  flutter_google_places_hoc081098: ^1.0.0-nullsafety.5
  google_api_headers: ^1.1.1
  rxdart: ^0.26.0
  geocoding: ^2.0.4
  bottom_navy_bar: ^6.0.0
  grouped_buttons: ^1.0.4
  dio: ^4.0.6
#  flutter_background_service: ^1.0.2

dependency_overrides:
  cloud_firestore_platform_interface: 5.4.13
  firebase_auth_platform_interface: 6.1.11
  firebase_database_platform_interface: 0.2.0+5


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:           # new
    sdk: flutter              # new
  test: ^1.14.4

flutter:
  uses-material-design: true

  assets:
    - images/