name: salama
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  modal_progress_hud: ^0.1.3
  flutter_map: ^0.14.0
  google_sign_in: ^5.2.4
  firebase_database: ^9.0.7
  http: ^0.13.4
  google_maps_flutter: ^2.1.1
  location: ^4.3.0
  provider: ^6.0.2
  geolocator: ^8.0.0

dependency_overrides:
  cloud_firestore_platform_interface: 5.4.13
  firebase_auth_platform_interface: 6.1.11
  firebase_database_platform_interface: 0.2.0+5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/